name: "StaticCheck"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "staticcheck"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@9716614d4101e79b4340dd97b10e54d68234e431 # v1.4.1
      with:
        version: "2024.1.1"
