name: "StaticCheck"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "staticcheck"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: "2024.1.1"
